services:
  frontend-app:
    build: .
    environment:
      APP_ENV: DEV
      WORKING_DIR: /opt/services/app
    user: "root:root"
    working_dir: /opt/services/frontend
    volumes:
      - ../../frontend:/opt/services/frontend:cached
      - ../../logs/frontend-app:/opt/services/log:cached
      - ../../media:/opt/services/media
      - ../ssl:/opt/services/ssl
      - ./local.nginx.setting:/etc/nginx/sites-available/local.nginx.setting
      - ./start.sh:/opt/services/start.sh
    command: /bin/bash -c "/opt/services/start.sh"